import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { App } from './app/app';
import {
  ModuleRegistry,
  ValidationModule,
  ColumnAutoSizeModule,
  ColumnHoverModule,
  PinnedRowModule,
  RowAutoHeightModule,
  RowStyleModule,
  PaginationModule,
  RowDragModule,
  CellSpanModule,
  CellStyleModule,
  HighlightChangesModule,
  TooltipModule,
  TextFilterModule,
  NumberFilterModule,
  DateFilterModule,
  CustomFilterModule,
  ExternalFilterModule,
  QuickFilterModule,
  RowSelectionModule,
  TextEditorModule,
  LargeTextEditorModule,
  CheckboxEditorModule,
  CustomEditorModule,
  LocaleModule,
  CsvExportModule,
  DragAndDropModule,
  ValueCacheModule,
  GridStateModule,
  ColumnApiModule,
  RowApiModule,
  CellApiModule,
  ScrollApiModule,
  RenderApiModule,
  EventApiModule,
  ClientSideRowModelApiModule,
  ClientSideRowModelModule,
} from 'ag-grid-community';

ModuleRegistry.registerModules([
  ValidationModule,
  ColumnAutoSizeModule,
  ColumnHoverModule,
  PinnedRowModule,
  RowAutoHeightModule,
  RowStyleModule,
  PaginationModule,
  RowDragModule,
  CellSpanModule,
  CellStyleModule,
  HighlightChangesModule,
  TooltipModule,
  TextFilterModule,
  NumberFilterModule,
  DateFilterModule,
  CustomFilterModule,
  ExternalFilterModule,
  QuickFilterModule,
  RowSelectionModule,
  TextEditorModule,
  LargeTextEditorModule,
  CheckboxEditorModule,
  CustomEditorModule,
  LocaleModule,
  CsvExportModule,
  DragAndDropModule,
  ValueCacheModule,
  GridStateModule,
  ColumnApiModule,
  RowApiModule,
  CellApiModule,
  ScrollApiModule,
  RenderApiModule,
  EventApiModule,
  ClientSideRowModelApiModule,
  ClientSideRowModelModule,
]);

bootstrapApplication(App, appConfig)
  .catch((err) => console.error(err));
